# Generated by Django 3.0.2 on 2020-02-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='city',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='adrress1',
            new_name='linha1',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='adrress2',
            new_name='linha2',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='country',
            new_name='pais',
        ),
        migrations.AddField(
            model_name='endereco',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
